events.listen('item.registry', function (e) {
  e.create('ultimate_netherite').displayName('Ultimate Netherite Ingot')
  e.create('platinum_ingot').displayName('Platinum Ingot')
  e.create('tungsten_ingot').displayName('Tungsten Ingot')
  e.create('platinum_nugget').displayName('Platinum Nugget')
  e.create('tungsten_nugget').displayName('Tungsten Nugget')
  e.create('inferium_seed').displayName('§eInferium Seed Base')
  e.create('prudentium_seed').displayName('§2Prudentium Seed Base')
  e.create('tertium_seed').displayName('§6Tertium Seed Base')
  e.create('imperium_seed').displayName('§9Imperium Seed Base')
  e.create('supremium_seed').displayName('§cSupremium Seed Base')
  e.create('insanium_seed').displayName('§5Insanium Seed Base')
  e.create('ultimate_seed').displayName('Ultimate Seed')
  e.create('ultimate_essence').displayName('Ultimate Essence')
  e.create('ultimate_netherite_lattice').displayName('Ultimate Netherite Lattice')
  e.create('sphere').displayName('Sphere Of All Things')
  e.create('brass_plate').displayName('Brass Plate')
  e.create('lapis_plate').displayName('Lapis Plate')
  e.create('zinc_plate').displayName('Zinc Plate')
  e.create('etherium_photovoltaic_cell').displayName('Etherium Photovoltaic Cell')
  e.create('gobber_photovoltaic_cell').displayName('Gobber Photovoltaic Cell')
  e.create('ultimate_photovoltaic_cell').displayName('Ultimate Photovoltaic Cell')
  e.create('pile_of_quarkonium').displayName('Pile Of Quarkonium')
  e.create('quarkonium_nugget').displayName('Quarkonium Nugget')
  e.create('quarkonium_ingot').displayName('Quarkonium Ingot')
  e.create('machinarium_ingot').displayName('Machinarium Ingot')
  e.create('creative_plate').displayName('Creative Plate').glow(true)
  e.create('incomplete_draconium').displayName('Incomplete Draconium Ingot').glow(true)
  e.create('antimatter_silicon').displayName('Tiny Antimatter Rubber').glow(true)
  e.create('loading_pearl').displayName('Loading Pearl')
  e.create('emc1').displayName('Clumped Ichi EMC')
  e.create('emc2').displayName('Clumped Ni EMC')
  e.create('emc3').displayName('Clumped San EMC')
  e.create('emc4').displayName('Clumped Yon EMC')
  e.create('emc5').displayName('Clumped Go EMC')

  //Skyblock
  e.create('ragnamod_6_sky:piece_iron').displayName('Iron Ore Piece')
  e.create('ragnamod_6_sky:piece_gold').displayName('Gold Ore Piece')
  e.create('ragnamod_6_sky:piece_aluminum').displayName('Aluminium Ore Piece')
  e.create('ragnamod_6_sky:piece_uranium').displayName('Uranium Ore Piece')
  e.create('ragnamod_6_sky:piece_zinc').displayName('Zinc Ore Piece')
  e.create('ragnamod_6_sky:piece_tungsten').displayName('Tungsten Ore Piece')
  e.create('ragnamod_6_sky:piece_osmium').displayName('Osmium Ore Piece')
  e.create('ragnamod_6_sky:piece_copper').displayName('Copper Ore Piece')
  e.create('ragnamod_6_sky:piece_tin').displayName('Tin Ore Piece')
  e.create('ragnamod_6_sky:piece_lead').displayName('Lead Ore Piece')
  e.create('ragnamod_6_sky:piece_silver').displayName('Silver Ore Piece')
  e.create('ragnamod_6_sky:piece_nickel').displayName('Nickel Ore Piece')
  e.create('ragnamod_6_sky:piece_cobalt').displayName('Cobalt Ore Piece')
  e.create('ragnamod_6_sky:piece_pendorite').displayName('Pendorite Ore Piece')
  e.create('ragnamod_6_sky:piece_emeraldite').displayName('Emeraldite Ore Piece')
  e.create('ragnamod_6_sky:piece_amber').displayName('Amber Ore Piece')
  e.create('ragnamod_6_sky:piece_ender').displayName('Ender Ore Piece')
  e.create('ragnamod_6_sky:piece_endumium').displayName('Endumium Ore Piece')
  e.create('ragnamod_6_sky:piece_soulium').displayName('Soulium Ore Piece')
  e.create('ragnamod_6_sky:piece_platinum').displayName('Platinum Ore Piece')
  e.create('ragnamod_6_sky:piece_source_gem').displayName('Source Gem Ore Piece')
  e.create('ragnamod_6_sky:chunk_iron').displayName('Iron Chunk')
  e.create('ragnamod_6_sky:chunk_gold').displayName('Gold Chunk')
  e.create('ragnamod_6_sky:chunk_aluminum').displayName('Aluminium Chunk')
  e.create('ragnamod_6_sky:chunk_uranium').displayName('Uranium Chunk')
  e.create('ragnamod_6_sky:chunk_zinc').displayName('Zinc Chunk')
  e.create('ragnamod_6_sky:chunk_tungsten').displayName('Tungsten Chunk')
  e.create('ragnamod_6_sky:chunk_osmium').displayName('Osmium Chunk')
  e.create('ragnamod_6_sky:chunk_copper').displayName('Copper Chunk')
  e.create('ragnamod_6_sky:chunk_tin').displayName('Tin Chunk')
  e.create('ragnamod_6_sky:chunk_lead').displayName('Lead Chunk')
  e.create('ragnamod_6_sky:chunk_silver').displayName('Silver Chunk')
  e.create('ragnamod_6_sky:chunk_nickel').displayName('Nickel Chunk')
  e.create('ragnamod_6_sky:chunk_cobalt').displayName('Cobalt Chunk')
  e.create('ragnamod_6_sky:chunk_pendorite').displayName('Pendorite Chunk')
  e.create('ragnamod_6_sky:chunk_emeraldite').displayName('Emeraldite Chunk')
  e.create('ragnamod_6_sky:chunk_amber').displayName('Amber Chunk')
  e.create('ragnamod_6_sky:chunk_ender').displayName('Ender Chunk')
  e.create('ragnamod_6_sky:chunk_endumium').displayName('Endumium Chunk')
  e.create('ragnamod_6_sky:chunk_soulium').displayName('Soulium Chunk')
  e.create('ragnamod_6_sky:chunk_platinum').displayName('Platinum Chunk')
  e.create('ragnamod_6_sky:chunk_source_gem').displayName('Source Gem Chunk')
  e.create('ragnamod_6_sky:andesite_pebble').displayName('Andesite Pebble')
  e.create('ragnamod_6_sky:blackstone_pebble').displayName('Blackstone Pebble')
  e.create('ragnamod_6_sky:cobble_pebble').displayName('Cobble Pebble')
  e.create('ragnamod_6_sky:deepslate_pebble').displayName('Deepslate Pebble')
  e.create('ragnamod_6_sky:diorite_pebble').displayName('Diorite Pebble')
  e.create('ragnamod_6_sky:granite_pebble').displayName('Granite Pebble')
  e.create('ragnamod_6_sky:gabbro_pebble').displayName('Gabbro Pebble')
  e.create('ragnamod_6_sky:basalt_pebble').displayName('Basalt Pebble')
})